create table tb_account
(
    created_at timestamp(6) with time zone,
    id         bigint generated by default as identity,
    status     varchar(255) not null check ((status in ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'BANNED'))),
    primary key (id)
);
